{{- if not .Values.s3.existingSecret }}
{{- $secretName := printf "%s-credentials" .Release.Name }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  {{- if $existing.data }}
  accessKeyId: {{ index $existing.data "accessKeyId" }}
  secretAccessKey: {{ index $existing.data "secretAccessKey" }}
  {{- else }}
  accessKeyId: {{ .Values.superAdmin.username | b64enc | quote }}
  secretAccessKey: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
